services:
  db:
    image: mongo
    container_name: mongo-database
    restart: always
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      MONGO_URL: "mongodb://mongo-database:27017/app"
      JWT_SECRET: "my-secret-password"
      APP_ENV: dev
    depends_on:
      - db
